/** Stable save-state identifiers. Keep these names independent of constructor/minifier behavior. */
export const GAME_ELEMENT_TYPE_IDS = [
    "Airplane",
    "AppearingBrownTank",
    "AppearingEnemyHelicopter",
    "AppearingGrayJeep",
    "AppearingPlane",
    "AppearingSoldier",
    "Bomb",
    "BossBlueTank",
    "BossBlueTanksManager",
    "BossGarage",
    "BossGarageManager",
    "BossHeadquarters",
    "BossHeadquartersManager",
    "BossHelicopter",
    "BossHelicopterManager",
    "BossShipGun",
    "BossShipManager",
    "BossStatue",
    "BossStatuesManager",
    "BossSuperTank",
    "BossSuperTankGun",
    "BrownTank",
    "BulletHit",
    "CannonTruck",
    "Chinook",
    "CliffGun",
    "CliffMissileLauncher",
    "Column",
    "DeadEnemySoldier",
    "ElephantGun",
    "ElephantMissile",
    "EnemyBullet",
    "EnemyHelicopter",
    "EnemySoldier",
    "Explosion",
    "Fire",
    "FireTank",
    "Flame",
    "FlashingSkull",
    "FloorGun",
    "FloorMissileLauncher",
    "FriendlyHelicopter",
    "FriendlySoldier",
    "Gate",
    "GrayBoat",
    "GrayJeep",
    "GrayTank",
    "GreenBoat",
    "Grenade",
    "Help",
    "House",
    "Hut",
    "IntroPlayer",
    "InvisibleStar",
    "LandingPort",
    "Laser",
    "LasersManager",
    "Mine",
    "MissionAccomplished",
    "Parachute",
    "ParkedBrownTank",
    "ParkedGrayJeep",
    "PlayerBullet",
    "PlayerMissile",
    "Rock",
    "RotatingGun",
    "Star",
    "Statue",
    "StatueMissile",
    "StatueSeekerMissile",
    "Submarine",
    "SubmarineMissile",
    "SuperFire",
    "SwampMissile",
    "SwampMissileLauncher",
    "TileDebris",
    "Train",
    "TrainManager",
    "TravelingExplosion",
    "TroopsTruck"
] as const;

export type GameElementTypeId = (typeof GAME_ELEMENT_TYPE_IDS)[number];

const GAME_ELEMENT_TYPE_ID_SET: ReadonlySet<string> = new Set(GAME_ELEMENT_TYPE_IDS);

export function isGameElementTypeId(value: unknown): value is GameElementTypeId {
    return typeof value === "string" && GAME_ELEMENT_TYPE_ID_SET.has(value);
}
