import { javaFloat } from "../../java/JavaRuntime.js";
import type { GameElementTypeId } from "./GameElementTypeIds.js";
import type { StandaloneModeId } from "./GameStateFields.js";

/**
 * Java rounds every assignment to a float field or float-array element to IEEE-754 binary32.
 * Production updates already preserve those storage boundaries. These tables normalize snapshots
 * written by older PWA builds, whose Number values may still contain binary64-only state.
 *
 * This code runs only while restoring a save; it adds no work to the 100 TPS gameplay loop.
 */
export type JavaFloatStateField = readonly [name: string, arrayDepth: number];
export type JavaFloatStateSpec = readonly JavaFloatStateField[];
export const MAIN_JAVA_FLOAT_FIELDS: JavaFloatStateSpec = [["unitVector", 1]];
export const GAME_MODE_JAVA_FLOAT_FIELDS: JavaFloatStateSpec = [
    ["conveyorOffset", 0],
    ["conveyorDelta", 0],
    ["cameraX", 0],
    ["cameraY", 0],
    ["maxCameraX", 0],
    ["maxCameraY", 0]
];
export const PLAYER_JAVA_FLOAT_FIELDS: JavaFloatStateSpec = [
    ["x", 0],
    ["y", 0],
    ["displayAngle", 0],
    ["angleVelocity", 0]
];
export const MENU_JAVA_FLOAT_FIELDS: JavaFloatStateSpec = [
    ["x", 0],
    ["y", 0],
    ["iconY", 0],
    ["iconVy", 0],
    ["iconMidY", 0],
    ["iconA", 0],
    ["targetY", 0]
];
export const INTRO_MODE_JAVA_FLOAT_FIELDS: JavaFloatStateSpec = [
    ["scrollOffsetX", 0],
    ["upperSolderX", 0],
    ["lowerSolderX", 0]
];
export const CONTINUE_MODE_JAVA_FLOAT_FIELDS: JavaFloatStateSpec = [];
export const DIFFICULTY_MODE_JAVA_FLOAT_FIELDS: JavaFloatStateSpec = [];
export const OPTIONS_MODE_JAVA_FLOAT_FIELDS: JavaFloatStateSpec = [];
export const INPUT_MODE_JAVA_FLOAT_FIELDS: JavaFloatStateSpec = [];
export const INTRO_MAP_MODE_JAVA_FLOAT_FIELDS: JavaFloatStateSpec = [];
export const MAP_MODE_JAVA_FLOAT_FIELDS: JavaFloatStateSpec = [
    ["jeepY", 0],
    ["targetJeepY", 0]
];
export const JEEP_HERE_MODE_JAVA_FLOAT_FIELDS: JavaFloatStateSpec = [["jeepHereX", 0]];
export const JEEP_YEAH_MODE_JAVA_FLOAT_FIELDS: JavaFloatStateSpec = [
    ["smokeX", 0],
    ["smokeY", 0]
];
export const JEEP_YEAH_PLANE_JAVA_FLOAT_FIELDS: JavaFloatStateSpec = [
    ["x", 0],
    ["y", 0],
    ["z", 0],
    ["angle", 0]
];
export const JEEP_YEAH_EXPLOSION_JAVA_FLOAT_FIELDS: JavaFloatStateSpec = [
    ["size", 0],
    ["scale", 0],
    ["alpha", 0],
    ["enemyX", 0],
    ["enemyY", 0],
    ["x", 0],
    ["y", 0]
];
export const JEEP_YEAH_FIRE_LEFT_JAVA_FLOAT_FIELDS: JavaFloatStateSpec = [
    ["scale", 0],
    ["x", 0],
    ["y", 0]
];
export const JEEP_YEAH_FIRE_RIGHT_JAVA_FLOAT_FIELDS: JavaFloatStateSpec = [
    ["scale", 0],
    ["x", 0],
    ["y", 0]
];
export const JEEP_YEAH_BULLET_JAVA_FLOAT_FIELDS: JavaFloatStateSpec = [
    ["x", 0],
    ["y", 0],
    ["vx", 0],
    ["vy", 0],
    ["angle", 0],
    ["scale", 0]
];
export const SUNSET_MODE_JAVA_FLOAT_FIELDS: JavaFloatStateSpec = [
    ["rotorAngle", 0],
    ["helicopterX", 0],
    ["helicopterY", 0],
    ["helicopterZ", 0],
    ["helicopterAngle", 0]
];
export const HARD_ENDING_MODE_JAVA_FLOAT_FIELDS: JavaFloatStateSpec = [
    ["finalScoreX", 0],
    ["creditsY", 0],
    ["jeepX", 0]
];

export const GAME_ELEMENT_JAVA_FLOAT_FIELDS: Readonly<Record<GameElementTypeId, JavaFloatStateSpec>> = {
    Airplane: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0]
    ],
    AppearingBrownTank: [
        ["x", 0],
        ["y", 0]
    ],
    AppearingEnemyHelicopter: [
        ["x", 0],
        ["y", 0]
    ],
    AppearingGrayJeep: [
        ["x", 0],
        ["y", 0]
    ],
    AppearingPlane: [
        ["x", 0],
        ["y", 0]
    ],
    AppearingSoldier: [
        ["x", 0],
        ["y", 0]
    ],
    Bomb: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0],
        ["vx", 0],
        ["vy", 0],
        ["scale", 0],
        ["angle", 0]
    ],
    BossBlueTank: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0],
        ["displayAngle", 0],
        ["directionX", 0],
        ["directionY", 0],
        ["vx", 0],
        ["vy", 0],
        ["sensorX", 0],
        ["sensorY", 0],
        ["lastDx", 0],
        ["lastDy", 0],
        ["loopTargetX", 0],
        ["loopTargetY", 0],
        ["introVy", 0]
    ],
    BossBlueTanksManager: [
        ["x", 0],
        ["y", 0]
    ],
    BossGarage: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0],
        ["doorY", 0],
        ["vehicleY", 0]
    ],
    BossGarageManager: [
        ["x", 0],
        ["y", 0],
        ["sparkX", 0]
    ],
    BossHeadquarters: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0]
    ],
    BossHeadquartersManager: [
        ["x", 0],
        ["y", 0]
    ],
    BossHelicopter: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0],
        ["angle", 0],
        ["rotorAngle", 0],
        ["positionDriftDx", 0],
        ["positionDriftDy", 0],
        ["vy", 0],
        ["va", 0]
    ],
    BossHelicopterManager: [
        ["x", 0],
        ["y", 0]
    ],
    BossShipGun: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0],
        ["openY", 0],
        ["angle", 0],
        ["aimingSpeed", 0]
    ],
    BossShipManager: [
        ["x", 0],
        ["y", 0]
    ],
    BossStatue: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0]
    ],
    BossStatuesManager: [
        ["x", 0],
        ["y", 0]
    ],
    BossSuperTank: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0],
        ["wheelAngle", 0],
        ["treadOffset", 0],
        ["vx", 0],
        ["targetX", 0],
        ["ax", 0],
        ["smashed", 0]
    ],
    BossSuperTankGun: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0],
        ["angle", 0],
        ["recoil", 0]
    ],
    BrownTank: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0],
        ["displayAngle", 0],
        ["directionX", 0],
        ["directionY", 0],
        ["vx", 0],
        ["vy", 0],
        ["sensorX", 0],
        ["sensorY", 0],
        ["lastDx", 0],
        ["lastDy", 0],
        ["loopTargetX", 0],
        ["loopTargetY", 0]
    ],
    BulletHit: [
        ["x", 0],
        ["y", 0]
    ],
    CannonTruck: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0]
    ],
    Chinook: [
        ["x", 0],
        ["y", 0],
        ["angle", 0],
        ["rotorAngle", 0],
        ["z", 0],
        ["vt", 0],
        ["t", 0],
        ["X", 0],
        ["Y", 0]
    ],
    CliffGun: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0]
    ],
    CliffMissileLauncher: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0]
    ],
    Column: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0],
        ["rotationOffset", 0],
        ["angle", 0],
        ["vx", 0],
        ["vy", 0],
        ["angleInc", 0]
    ],
    DeadEnemySoldier: [
        ["x", 0],
        ["y", 0]
    ],
    ElephantGun: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0],
        ["asters", 2],
        ["fireballX", 0],
        ["fireballY", 0],
        ["fireballVx", 0]
    ],
    ElephantMissile: [
        ["x", 0],
        ["y", 0],
        ["angle", 0],
        ["vx", 0],
        ["vy", 0],
        ["maxY", 0],
        ["explosionOffset", 0],
        ["tipX", 0],
        ["tipY", 0]
    ],
    EnemyBullet: [
        ["x", 0],
        ["y", 0],
        ["vx", 0],
        ["vy", 0]
    ],
    EnemyHelicopter: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0],
        ["angle", 0],
        ["rotorAngle", 0],
        ["positionDriftDx", 0],
        ["positionDriftDy", 0],
        ["enteringAcceleration", 0],
        ["vy", 0],
        ["targetAngle", 0],
        ["targetHalfAngle", 0],
        ["va", 0],
        ["v", 0]
    ],
    EnemySoldier: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0],
        ["targetX", 0],
        ["targetY", 0],
        ["targetVx", 0],
        ["targetVy", 0],
        ["directionX", 0],
        ["directionY", 0],
        ["wobbleX", 0],
        ["wobbleY", 0],
        ["wobbleScaleX", 0],
        ["wobbleScaleY", 0]
    ],
    Explosion: [
        ["x", 0],
        ["y", 0],
        ["size", 0],
        ["scale", 0],
        ["alpha", 0],
        ["enemyX", 0],
        ["enemyY", 0]
    ],
    Fire: [
        ["x", 0],
        ["y", 0],
        ["vx", 0],
        ["vy", 0],
        ["dx", 0],
        ["dy", 0],
        ["length", 0],
        ["angle", 0],
        ["alpha", 0]
    ],
    FireTank: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0],
        ["displayAngle", 0],
        ["directionX", 0],
        ["directionY", 0],
        ["vx", 0],
        ["vy", 0],
        ["sensorX", 0],
        ["sensorY", 0],
        ["lastDx", 0],
        ["lastDy", 0],
        ["loopTargetX", 0],
        ["loopTargetY", 0]
    ],
    Flame: [
        ["x", 0],
        ["y", 0]
    ],
    FlashingSkull: [
        ["x", 0],
        ["y", 0],
        ["alpha", 0]
    ],
    FloorGun: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0],
        ["openY", 0],
        ["angle", 0],
        ["aimingSpeed", 0]
    ],
    FloorMissileLauncher: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0],
        ["panelOffset", 0]
    ],
    FriendlyHelicopter: [
        ["x", 0],
        ["y", 0],
        ["angle", 0],
        ["rotorAngle", 0],
        ["rotorSpeed", 0],
        ["z", 0],
        ["turnX", 0],
        ["turnY", 0]
    ],
    FriendlySoldier: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0],
        ["vx", 0],
        ["vy", 0],
        ["directionX", 0],
        ["directionY", 0],
        ["wobbleX", 0],
        ["wobbleY", 0],
        ["wobbleScaleX", 0],
        ["wobbleScaleY", 0]
    ],
    Gate: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0]
    ],
    GrayBoat: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0],
        ["gunAngle", 0]
    ],
    GrayJeep: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0],
        ["displayAngle", 0],
        ["directionX", 0],
        ["directionY", 0],
        ["vx", 0],
        ["vy", 0],
        ["sensorX", 0],
        ["sensorY", 0],
        ["lastDx", 0],
        ["lastDy", 0],
        ["loopTargetX", 0],
        ["loopTargetY", 0]
    ],
    GrayTank: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0],
        ["displayAngle", 0],
        ["directionX", 0],
        ["directionY", 0],
        ["vx", 0],
        ["vy", 0],
        ["sensorX", 0],
        ["sensorY", 0],
        ["lastDx", 0],
        ["lastDy", 0],
        ["loopTargetX", 0],
        ["loopTargetY", 0],
        ["shackX", 0],
        ["shackY", 0]
    ],
    GreenBoat: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0]
    ],
    Grenade: [
        ["x", 0],
        ["y", 0],
        ["vx", 0],
        ["vy", 0],
        ["scale", 0],
        ["angle", 0]
    ],
    Help: [
        ["x", 0],
        ["y", 0]
    ],
    House: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0]
    ],
    Hut: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0]
    ],
    IntroPlayer: [
        ["x", 0],
        ["y", 0],
        ["angle", 0]
    ],
    InvisibleStar: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0]
    ],
    LandingPort: [
        ["x", 0],
        ["y", 0]
    ],
    Laser: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0]
    ],
    LasersManager: [
        ["x", 0],
        ["y", 0]
    ],
    Mine: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0]
    ],
    MissionAccomplished: [
        ["x", 0],
        ["y", 0]
    ],
    Parachute: [
        ["x", 0],
        ["y", 0],
        ["vx", 0]
    ],
    ParkedBrownTank: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0]
    ],
    ParkedGrayJeep: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0]
    ],
    PlayerBullet: [
        ["x", 0],
        ["y", 0]
    ],
    PlayerMissile: [
        ["x", 0],
        ["y", 0],
        ["vx", 0],
        ["vy", 0],
        ["angle", 0]
    ],
    Rock: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0],
        ["angle", 0],
        ["scale", 0],
        ["vScale", 0],
        ["vx", 0],
        ["acceleration", 0]
    ],
    RotatingGun: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0],
        ["angle", 0],
        ["recoil", 0]
    ],
    Star: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0]
    ],
    Statue: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0]
    ],
    StatueMissile: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0],
        ["vx", 0],
        ["angle", 0],
        ["statueX", 0],
        ["statueY", 0],
        ["clipX", 0]
    ],
    StatueSeekerMissile: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0],
        ["vx", 0],
        ["vy", 0],
        ["angle", 0],
        ["statueX", 0],
        ["statueY", 0],
        ["clipX", 0]
    ],
    Submarine: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0],
        ["alpha", 0]
    ],
    SubmarineMissile: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0],
        ["vy", 0],
        ["vx", 0],
        ["tx", 0],
        ["ty", 0]
    ],
    SuperFire: [
        ["x", 0],
        ["y", 0],
        ["length", 0],
        ["flickerCounter", 0]
    ],
    SwampMissile: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0],
        ["vx", 0],
        ["vy", 0],
        ["angle", 0],
        ["launcherX", 0],
        ["launcherY", 0],
        ["clipX", 0]
    ],
    SwampMissileLauncher: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0]
    ],
    TileDebris: [
        ["x", 0],
        ["y", 0],
        ["vx", 0],
        ["vy", 0],
        ["scale", 0]
    ],
    Train: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0],
        ["shootX", 0],
        ["shootY", 0]
    ],
    TrainManager: [
        ["x", 0],
        ["y", 0]
    ],
    TravelingExplosion: [
        ["x", 0],
        ["y", 0],
        ["vx", 0],
        ["vy", 0],
        ["scale", 0]
    ],
    TroopsTruck: [
        ["x", 0],
        ["y", 0],
        ["hitX1", 0],
        ["hitY1", 0],
        ["hitX2", 0],
        ["hitY2", 0],
        ["solidX1", 0],
        ["solidY1", 0],
        ["solidX2", 0],
        ["solidY2", 0],
        ["mineX1", 0],
        ["mineY1", 0],
        ["mineX2", 0],
        ["mineY2", 0],
        ["explosionX", 0],
        ["explosionY", 0]
    ]
};

export const STANDALONE_MODE_JAVA_FLOAT_FIELDS: Readonly<Record<StandaloneModeId, JavaFloatStateSpec>> = {
    INTRO: INTRO_MODE_JAVA_FLOAT_FIELDS,
    HERE: JEEP_HERE_MODE_JAVA_FLOAT_FIELDS,
    YEAH: JEEP_YEAH_MODE_JAVA_FLOAT_FIELDS,
    WE_MADE_IT: JEEP_YEAH_MODE_JAVA_FLOAT_FIELDS,
    SUNSET: SUNSET_MODE_JAVA_FLOAT_FIELDS,
    HARD_ENDING: HARD_ENDING_MODE_JAVA_FLOAT_FIELDS,
    MAP: MAP_MODE_JAVA_FLOAT_FIELDS,
    CONTINUE: CONTINUE_MODE_JAVA_FLOAT_FIELDS,
    DIFFICULTY: DIFFICULTY_MODE_JAVA_FLOAT_FIELDS,
    OPTIONS: OPTIONS_MODE_JAVA_FLOAT_FIELDS,
    INPUT: INPUT_MODE_JAVA_FLOAT_FIELDS,
    INTRO_MAP: INTRO_MAP_MODE_JAVA_FLOAT_FIELDS
};

export function normalizeJavaFloatFields(target: object, fields: JavaFloatStateSpec): void {
    for (const [name, arrayDepth] of fields) {
        if (!Object.hasOwn(target, name)) {
            continue;
        }
        Reflect.set(target, name, normalizeJavaFloatValue(Reflect.get(target, name), arrayDepth));
    }
}

function normalizeJavaFloatValue(value: unknown, arrayDepth: number): unknown {
    if (arrayDepth === 0) {
        return typeof value === "number" ? javaFloat(value) : value;
    }
    if (!Array.isArray(value)) {
        return value;
    }
    for (let i = 0; i < value.length; i++) {
        value[i] = normalizeJavaFloatValue(value[i], arrayDepth - 1);
    }
    return value;
}
